# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.EmailField(max_length=30)),
                ('sname', models.CharField(max_length=40)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
    ]
