# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp_data',
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
